### PR TITLE
feat: add missing arcpy members for pylint

### PR DESCRIPTION
**Pull request by stdavis**

### CODE REVIEW

**Comment by jacobdadams** [comment]
Cool, I was unaware of this option.

Part of me wants to just use `arcpy.*`, but I realize that has the potential to cause us to miss a lot of mis-spellings, etc. On the other hand, I think this could become an ever-growing list of exceptions as we find different things that raise this error. 

#MondayMorningMusingsMissingMeaningfulMeanings

**Comment by steveoh** [comment]
> ... I think this could become an ever-growing list of exceptions as we find different things that raise this error.

I am ok with that. I would rather create an exceptions list than the opposite.

**Comment by stdavis** [comment]
FWIW it appears that the `arcpy.da` module is the only one that throws these errors that I've noticed. I wonder if it's defined differently so that pylint can't find its members.

**Comment by jacobdadams** [comment]
I've also seen it in the arcgis library- things like `gis_object.users.me` and `gis_object.content.get()`. I'll put together a list later and submit it as a PR.

**Pull request merged**
